//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resource.BasicInput {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BasicInputRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicInputRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resource.BasicInput.BasicInputRes", typeof(BasicInputRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advertisment.
        /// </summary>
        public static string AddAdds {
            get {
                return ResourceManager.GetString("AddAdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Branch.
        /// </summary>
        public static string AddBranch {
            get {
                return ResourceManager.GetString("AddBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCategory.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category Property Name.
        /// </summary>
        public static string AddCategoryPropName {
            get {
                return ResourceManager.GetString("AddCategoryPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category Property Type.
        /// </summary>
        public static string AddCategoryPropType {
            get {
                return ResourceManager.GetString("AddCategoryPropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Delivery Method.
        /// </summary>
        public static string AddDeliveryMethod {
            get {
                return ResourceManager.GetString("AddDeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offer.
        /// </summary>
        public static string AddOffer {
            get {
                return ResourceManager.GetString("AddOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offers Sub.
        /// </summary>
        public static string AddOffersSub {
            get {
                return ResourceManager.GetString("AddOffersSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment.
        /// </summary>
        public static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Plans.
        /// </summary>
        public static string AddPlans {
            get {
                return ResourceManager.GetString("AddPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Property.
        /// </summary>
        public static string AddProductProp {
            get {
                return ResourceManager.GetString("AddProductProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Details.
        /// </summary>
        public static string AddsDetails {
            get {
                return ResourceManager.GetString("AddsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stage.
        /// </summary>
        public static string AddStage {
            get {
                return ResourceManager.GetString("AddStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stocks.
        /// </summary>
        public static string AddStocks {
            get {
                return ResourceManager.GetString("AddStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address( AR ).
        /// </summary>
        public static string AdressAr {
            get {
                return ResourceManager.GetString("AdressAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address ( EN ).
        /// </summary>
        public static string AdressEn {
            get {
                return ResourceManager.GetString("AdressEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Dayes.
        /// </summary>
        public static string AverageDayes {
            get {
                return ResourceManager.GetString("AverageDayes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Per Order.
        /// </summary>
        public static string AveragePerOrder {
            get {
                return ResourceManager.GetString("AveragePerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Times.
        /// </summary>
        public static string AverageTimes {
            get {
                return ResourceManager.GetString("AverageTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Details.
        /// </summary>
        public static string BranchDetails {
            get {
                return ResourceManager.GetString("BranchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string CategoryDetails {
            get {
                return ResourceManager.GetString("CategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Property Name.
        /// </summary>
        public static string CategoryPropName {
            get {
                return ResourceManager.GetString("CategoryPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Property Name Details.
        /// </summary>
        public static string CategoryPropNameDetails {
            get {
                return ResourceManager.GetString("CategoryPropNameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Property Type Details.
        /// </summary>
        public static string CategoryPropTypeDetails {
            get {
                return ResourceManager.GetString("CategoryPropTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Property Types.
        /// </summary>
        public static string CategoryPropTypes {
            get {
                return ResourceManager.GetString("CategoryPropTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string CategPropType {
            get {
                return ResourceManager.GetString("CategPropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayes To Fill.
        /// </summary>
        public static string DayesToFill {
            get {
                return ResourceManager.GetString("DayesToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method Details.
        /// </summary>
        public static string DeliveryMethodDetails {
            get {
                return ResourceManager.GetString("DeliveryMethodDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ( AR ).
        /// </summary>
        public static string DescAr {
            get {
                return ResourceManager.GetString("DescAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ( EN ).
        /// </summary>
        public static string DescEn {
            get {
                return ResourceManager.GetString("DescEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ( Ar ).
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ( En ).
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disscount.
        /// </summary>
        public static string Disscount {
            get {
                return ResourceManager.GetString("Disscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Visalble.
        /// </summary>
        public static string EndDateVisalble {
            get {
                return ResourceManager.GetString("EndDateVisalble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experince.
        /// </summary>
        public static string Experince {
            get {
                return ResourceManager.GetString("Experince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Book.
        /// </summary>
        public static string FaceBook {
            get {
                return ResourceManager.GetString("FaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Order.
        /// </summary>
        public static string FinishOrder {
            get {
                return ResourceManager.GetString("FinishOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Details.
        /// </summary>
        public static string GroupDetails {
            get {
                return ResourceManager.GetString("GroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instgram.
        /// </summary>
        public static string Instgram {
            get {
                return ResourceManager.GetString("Instgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string IsBlock {
            get {
                return ResourceManager.GetString("IsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is For Another User.
        /// </summary>
        public static string IsForAnotherUser {
            get {
                return ResourceManager.GetString("IsForAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Order Value.
        /// </summary>
        public static string MinimumOrderValue {
            get {
                return ResourceManager.GetString("MinimumOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ( Ar ).
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ( En ).
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Number.
        /// </summary>
        public static string NextStadge {
            get {
                return ResourceManager.GetString("NextStadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Detail.
        /// </summary>
        public static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Sub Detail.
        /// </summary>
        public static string OffersSubDetails {
            get {
                return ResourceManager.GetString("OffersSubDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Stadge.
        /// </summary>
        public static string OrderStadge {
            get {
                return ResourceManager.GetString("OrderStadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pintrest.
        /// </summary>
        public static string Pintrest {
            get {
                return ResourceManager.GetString("Pintrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans Details.
        /// </summary>
        public static string PlansDetails {
            get {
                return ResourceManager.GetString("PlansDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Time.
        /// </summary>
        public static string Preparing_Time {
            get {
                return ResourceManager.GetString("Preparing_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price After Disscount.
        /// </summary>
        public static string priceAfterDisscount {
            get {
                return ResourceManager.GetString("priceAfterDisscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price In Subscription Per Month.
        /// </summary>
        public static string PriceInSubscriptionPerMonth {
            get {
                return ResourceManager.GetString("PriceInSubscriptionPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price In Subscription Per Year.
        /// </summary>
        public static string PriceInSubscriptionPerYear {
            get {
                return ResourceManager.GetString("PriceInSubscriptionPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Month.
        /// </summary>
        public static string PricePerMonth {
            get {
                return ResourceManager.GetString("PricePerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Year.
        /// </summary>
        public static string PricePerYear {
            get {
                return ResourceManager.GetString("PricePerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Product Main  Data.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Count.
        /// </summary>
        public static string ProductsCount {
            get {
                return ResourceManager.GetString("ProductsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Property Detail.
        /// </summary>
        public static string ProductsPropDetails {
            get {
                return ResourceManager.GetString("ProductsPropDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Related.
        /// </summary>
        public static string ProductsRelated {
            get {
                return ResourceManager.GetString("ProductsRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Type.
        /// </summary>
        public static string ProductsType {
            get {
                return ResourceManager.GetString("ProductsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        public static string PropName {
            get {
                return ResourceManager.GetString("PropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Type.
        /// </summary>
        public static string RegionType {
            get {
                return ResourceManager.GetString("RegionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Holders List.
        /// </summary>
        public static string RolesHoldersList {
            get {
                return ResourceManager.GetString("RolesHoldersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description ( AR ).
        /// </summary>
        public static string ShortDescAr {
            get {
                return ResourceManager.GetString("ShortDescAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description ( EN ).
        /// </summary>
        public static string ShortDescEn {
            get {
                return ResourceManager.GetString("ShortDescEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Details.
        /// </summary>
        public static string StageDetails {
            get {
                return ResourceManager.GetString("StageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks Details.
        /// </summary>
        public static string StocksDetails {
            get {
                return ResourceManager.GetString("StocksDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit Time.
        /// </summary>
        public static string Transit_Time {
            get {
                return ResourceManager.GetString("Transit_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userس List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Platform Type.
        /// </summary>
        public static string YourPlatformType {
            get {
                return ResourceManager.GetString("YourPlatformType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
