//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resource.GlobalRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resource.GlobalRes.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds.
        /// </summary>
        public static string Adds {
            get {
                return ResourceManager.GetString("Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin DashBoard.
        /// </summary>
        public static string AdminDashBoard {
            get {
                return ResourceManager.GetString("AdminDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements &amp; News.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller.
        /// </summary>
        public static string BestSeller {
            get {
                return ResourceManager.GetString("BestSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branche {
            get {
                return ResourceManager.GetString("Branche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string btnAddNewEmployee {
            get {
                return ResourceManager.GetString("btnAddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Property.
        /// </summary>
        public static string btnAddNewProp {
            get {
                return ResourceManager.GetString("btnAddNewProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string btnAddNewUser {
            get {
                return ResourceManager.GetString("btnAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product.
        /// </summary>
        public static string btnAddProduct {
            get {
                return ResourceManager.GetString("btnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string btnApprove {
            get {
                return ResourceManager.GetString("btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string btnCategoryPropName {
            get {
                return ResourceManager.GetString("btnCategoryPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clients.
        /// </summary>
        public static string btnClientList {
            get {
                return ResourceManager.GetString("btnClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Shift.
        /// </summary>
        public static string btnCount {
            get {
                return ResourceManager.GetString("btnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string btnExportExcel {
            get {
                return ResourceManager.GetString("btnExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel.
        /// </summary>
        public static string btnImportExcel {
            get {
                return ResourceManager.GetString("btnImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Roles .
        /// </summary>
        public static string btnRolesHolders {
            get {
                return ResourceManager.GetString("btnRolesHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save  And Exist.
        /// </summary>
        public static string btnSaveExist {
            get {
                return ResourceManager.GetString("btnSaveExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string btnShowAll {
            get {
                return ResourceManager.GetString("btnShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Property Names.
        /// </summary>
        public static string CategoryPropName {
            get {
                return ResourceManager.GetString("CategoryPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Property Type.
        /// </summary>
        public static string CategoryPropType {
            get {
                return ResourceManager.GetString("CategoryPropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string ChangePasswordSuccuss {
            get {
                return ResourceManager.GetString("ChangePasswordSuccuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients List.
        /// </summary>
        public static string ClientsList {
            get {
                return ResourceManager.GetString("ClientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Profile.
        /// </summary>
        public static string CompanyProfile {
            get {
                return ResourceManager.GetString("CompanyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the current password correctly.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Reviews.
        /// </summary>
        public static string CustomerReviews {
            get {
                return ResourceManager.GetString("CustomerReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Methods.
        /// </summary>
        public static string DeliveryMethod {
            get {
                return ResourceManager.GetString("DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Items.
        /// </summary>
        public static string ForItems {
            get {
                return ResourceManager.GetString("ForItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateExcel.
        /// </summary>
        public static string GenerateExcel {
            get {
                return ResourceManager.GetString("GenerateExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneratePDF.
        /// </summary>
        public static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in first.
        /// </summary>
        public static string LoginBefore {
            get {
                return ResourceManager.GetString("LoginBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginU {
            get {
                return ResourceManager.GetString("LoginU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Stores.
        /// </summary>
        public static string ManageStores {
            get {
                return ResourceManager.GetString("ManageStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Succuss.
        /// </summary>
        public static string Messagedelete {
            get {
                return ResourceManager.GetString("Messagedelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Shure To Delete Data.
        /// </summary>
        public static string MessageDeleteDate {
            get {
                return ResourceManager.GetString("MessageDeleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been e-mailed to you.
        /// </summary>
        public static string MessageEmailSent {
            get {
                return ResourceManager.GetString("MessageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Please try Again .
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageErrorSelectedUser.
        /// </summary>
        public static string MessageErrorSelectedUser {
            get {
                return ResourceManager.GetString("MessageErrorSelectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Data Not Valid.
        /// </summary>
        public static string MessageExcelError {
            get {
                return ResourceManager.GetString("MessageExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is already in the cart.
        /// </summary>
        public static string MessageExistInCart {
            get {
                return ResourceManager.GetString("MessageExistInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is already in the favourites.
        /// </summary>
        public static string MessageExistInFavorite {
            get {
                return ResourceManager.GetString("MessageExistInFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product not exist in the cart.
        /// </summary>
        public static string MessageNotExistInCart {
            get {
                return ResourceManager.GetString("MessageNotExistInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Row Or More To Delete.
        /// </summary>
        public static string MessageSelectRow {
            get {
                return ResourceManager.GetString("MessageSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Succuss.
        /// </summary>
        public static string MessageSuccuss {
            get {
                return ResourceManager.GetString("MessageSuccuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Succuss.
        /// </summary>
        public static string MessageUpdate {
            get {
                return ResourceManager.GetString("MessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Offers.
        /// </summary>
        public static string NewOffers {
            get {
                return ResourceManager.GetString("NewOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ptoducts.
        /// </summary>
        public static string NewPtoducts {
            get {
                return ResourceManager.GetString("NewPtoducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Management.
        /// </summary>
        public static string OfferManagement {
            get {
                return ResourceManager.GetString("OfferManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers Sub.
        /// </summary>
        public static string OffersSub {
            get {
                return ResourceManager.GetString("OffersSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Inquiry.
        /// </summary>
        public static string OrderInquiry {
            get {
                return ResourceManager.GetString("OrderInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management.
        /// </summary>
        public static string OrderManagement {
            get {
                return ResourceManager.GetString("OrderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Stages.
        /// </summary>
        public static string OrderStages {
            get {
                return ResourceManager.GetString("OrderStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our trendy products.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some products we have selected for your best choice.
        /// </summary>
        public static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Properties.
        /// </summary>
        public static string ProductsProp {
            get {
                return ResourceManager.GetString("ProductsProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Holders.
        /// </summary>
        public static string RolesHolders {
            get {
                return ResourceManager.GetString("RolesHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomSetting.
        /// </summary>
        public static string RoomSetting {
            get {
                return ResourceManager.GetString("RoomSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchResult.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show From.
        /// </summary>
        public static string ShowFrom {
            get {
                return ResourceManager.GetString("ShowFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe OR.
        /// </summary>
        public static string subscribe2 {
            get {
                return ResourceManager.GetString("subscribe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated.
        /// </summary>
        public static string TopRated {
            get {
                return ResourceManager.GetString("TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
